version: "3.5"

services:
  # Management Platform phpipam to manage docker stuff
  phpipam:
    image: pierrecdn/phpipam
    container_name: phpipam
    depends_on:
        - mariadb_test
    environment:
        - MYSQL_ENV_MYSQL_USER=root
        - MYSQL_ENV_MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_TEST}
        - MYSQL_ENV_MYSQL_HOST=mariadb
    restart: always
    labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.phpipam-secure.redirectscheme.scheme=https"
        - "traefik.http.routers.phpipam.middlewares=phpipam-secure"
        - "traefik.http.routers.phpipam.rule=Host(`ipam.${SUB_DOMAIN_NAME}`) || Host(`ipam.${DOMAIN_NAME}`)"
        - "traefik.http.routers.phpipam.entrypoints=http"
        - "traefik.http.middlewares.phpipam.redirectscheme.scheme=https"
        - "traefik.http.routers.phpipam-secure.rule=Host(`ipam.${SUB_DOMAIN_NAME}`) || Host(`ipam.${DOMAIN_NAME}`)"
        - "traefik.http.routers.phpipam-secure.entrypoints=https"
        - "traefik.http.routers.phpipam-secure.tls=true"
        - "traefik.http.routers.phpipam-secure.tls.certResolver=azure"
        # Uncomment this label if your Traefik instance is using a specific Docker network and replace the network name 
        # This is not necessary if you set your default network in Traefik config/parameters
        #- "traefik.docker.network=noctrismediaserverdocker_proxy"
  