version: "3.5"

services:
  # Management Platform Portainer to manage docker stuff
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    ports:
 #     - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.portainer-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-secure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.services.portainer.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.portainer.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
#      - "traefik.http.services.portainer-secure.loadbalancer.server.port=80"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certResolver=azure"
      - "traefik.http.routers.portainer-secure.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.portainer-secure.tls.domains[0].sans=*.${SUB_DOMAIN_NAME}"
volumes:
  portainer_data: