version: "3.5"

services:
  traefik:
    image: "traefik:latest"
    restart: always
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api=true"
      - "--api.dashboard=true"
      #- "--api.insecure=true"
      - "--certificatesResolvers.myresolver.acme.email=${ACME_MAIL}"
      - "--certificatesResolvers.myresolver.acme.storage=/traefik_data/acme.json"
      - "--certificatesResolvers.myresolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.httpChallenge=true"
      - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=http"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DOCKER_VOL_MOUNT}/traefik:/traefik_data"
    labels:
      - "traefik.enable=true"
      # define some generic middlewares
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.*}`)"
      #- "traefik.http.routers.https-redirect.entrypoints=web"
      - "traefik.http.routers.api.middlewares=traefikbasicAuth"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.api.entrypoints=http"
      #- "traefik.http.routers.api.middlewares=https-redirect"
      - "traefik.http.routers.api-ssl.middlewares=traefikbasicAuth"
      - "traefik.http.routers.api-ssl.service=api@internal"
      - "traefik.http.routers.api-ssl.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.api-ssl.entrypoints=https"
      # - "traefik.http.middlewares.http-redirect.redirectscheme.schema=https"
      # - "traefik.http.middlewares.http-redirect.redirectscheme.permanent=true"
      # - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)"
      # - "traefik.http.routers.traefik-dashboard.entrypoints=web"
      # - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"
      # - "traefik.http.routers.traefik-dashboard.middlewares=traefikbasicAuth"
      - "traefik.http.middlewares.traefikbasicAuth.basicauth.users=${TRAEFIK_USER}:$$apr1$$6ltp1kg8$$V0mBDQSBNhrjEOGqEcCZP."
      # Enable API at some point
      # - "traefik.http.routers.traefikapi.service=api@internal"
      # - "traefik.http.routers.traefikapi.rule=Host(`api.traefik.${DOMAIN_NAME}`)"
      # - "traefik.http.routers.traefikapi.entrypoints=web"
       #Need to check this. Api not workingy yet
      # - "traefik.enable=true"
      
      # - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # - "traefik.http.middlewares.traefik-secure.redirectscheme.scheme=https"
      # - "traefik.http.routers.traefik.middlewares=traefik-secure"
      # - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      # - "traefik.http.routers.traefik.entrypoints=web"
      # - "traefik.http.middlewares.traefik.redirectscheme.scheme=https"
      # - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)"
      # - "traefik.http.routers.traefik-secure.entrypoints=webSecure"
      # - "traefik.http.routers.traefik-secure.tls=true"
      # - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"