version: "3"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK_SET=022 #optional
    volumes:
      - sonarr_data:/config
      - tv:/tv
      - downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`sonarr.lab.vanhoof.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.docker.network=mediaserverdocker_dmz"
    networks:
      - backend    
    restart: unless-stopped

volumes:
  sonarr_data:
    driver: "local"
    driver_opts:
      #Mountpoint: "/mnt/dockervol/portainer_data/_data"
      type: "nfs"
      o: "addr=10.32.1.3,nolock,soft,rw"
      #device: ":/mnt/jet/jet-lab-docker"
      device: ":/mnt/tank/system/dockervol/sonarr"

    tv:
    #name: "portainer_data"
      driver: "local"
      driver_opts:
        #Mountpoint: "/mnt/dockervol/portainer_data/_data"
        type: "nfs"
        o: "addr=10.32.1.3,nolock,soft,rw"
        #device: ":/mnt/jet/jet-lab-docker"
        device: ":/mnt/tank/media/parents/Tv Shows"
    
    downloads:
    #name: "portainer_data"
      driver: "local"
      driver_opts:
       #Mountpoint: "/mnt/dockervol/portainer_data/_data"
        type: "nfs"
        o: "addr=10.32.1.3,nolock,soft,rw"
        #device: ":/mnt/jet/jet-lab-docker"
        device: ":/mnt/tank/downloads/downloads"



networks:
  backend:
    external:
      name: mediaserverdocker_backend