version: "3"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK_SET=022 #optional
    volumes:
      - /mnt/dockervol/sonarr2:/config
      - /mnt/pmedia/Tv Shows:/tv
      - /mnt/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`sonarr.lab.vanhoof.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.docker.network=mediaserverdocker_dmz"
    networks:
      - backend    
    restart: unless-stopped

networks:
  backend:
    external:
      name: mediaserverdocker_backend