version: '3'

services:
  # The reverse proxy to all the internal dockers to ty this whole thing together
  nginx-proxy-manager:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx_proxy_manager
    restart: always
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - dmz
      - backend
    links:
      - nginx-proxy-manager-mariadb
    depends_on: 
      - nginx-proxy-manager-mariadb
    
  
  nginx-proxy-manager-mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx_proxy_manager_mariadb
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

volumes:
  nginx_proxy_manager_mariadb_data:

networks:
  dmz:
    driver: bridge
  backend:
    driver: bridge
