version: "3.5"

services:
  # Management Platform Portainer to manage docker stuff
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    ports:
      - 9000:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=webSecure"
      - "traefik.http.middlewares.portainer.redirectscheme.schema=https"
      - "traefik.http.middlewares.portainer.redirectscheme.permanent=true"
      - "traefik.http.routers.portainer-ssl.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer-ssl.entrypoints=webSecure"
      - "traefik.http.routers.portainer-ssl.tls=true"
      - "traefik.http.routers.portainer-ssl.tls.certresolver=myresolver"
 
volumes:
  portainer_data: