# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master develop

pool:
  name: 'home-lab-build-docker'

steps:
- bash: echo TRAEFIK_ENTRY_POINT=$(TRAEFIK_ENTRY_POINT) >> $(Build.StagingDirectory)/.env
- bash: echo TRAEFIK_ENTRY_POINT_PORT=$(TRAEFIK_ENTRY_POINT_PORT) >> $(Build.StagingDirectory)/.env
- bash: echo TZ=Europe/Brussels >> $(Build.StagingDirectory)/.env
- bash: echo DOMAIN_NAME=$(VS_DOMAIN_NAME) >> $(Build.StagingDirectory)/.env
- bash: echo DOCKER_VOL_MOUNT=$(DOCKER_VOL_MOUNT) >> $(Build.StagingDirectory)/.env
- bash: echo PATH_P_TV_SHOWS=$(PATH_P_TV_SHOWS) >> $(Build.StagingDirectory)/.env
- bash: echo PATH_P_MOVIES=$(PATH_P_MOVIES) >> $(Build.StagingDirectory)/.env
- bash: echo PATH_DOWNLOADS=$(PATH_DOWNLOADS) >> $(Build.StagingDirectory)/.env
- bash: echo PATH_LYCHEE=$(PATH_LYCHEE) >> $(Build.StagingDirectory)/.env
- bash: echo ACME_MAIL=$(ACME_MAIL) >> $(Build.StagingDirectory)/.env
- bash: echo PLEX_CLAIM=$(PLEX_CLAIM) >> $(Build.StagingDirectory)/.env
- bash: cat $(Build.StagingDirectory)/.env
- bash: pwd
- bash: docker-compose config
  displayName: Docker Compose Config
# - task: DockerCompose@0
#   displayName: Kill the running setup
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerComposeFile: '**/docker-compose.yml'
#     action: 'Run a Docker Compose command'
#     dockerComposeCommand: 'down'
- task: DockerCompose@0
  displayName: Deploy the Mediaserver in Lab
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d --remove-orphans'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'docker-media-server'
    publishLocation: 'pipeline'


    
