# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master develop

pool:
  name: 'home-lab-build-docker'

steps:
- bash: echo TRAEFIK_ENTRY_POINT=$(TRAEFIK_ENTRY_POINT) >> **/.env
- bash: echo TRAEFIK_ENTRY_POINT_PORT=$(TRAEFIK_ENTRY_POINT_PORT) >> **/.env
- bash: echo TZ=Europe/Brussels >> **/.env
- bash: echo DOMAIN_NAME=$(VS_DOMAIN_NAME) >> **/.env
- bash: echo DOCKER_VOL_MOUNT=$(DOCKER_VOL_MOUNT) >> **/.env
- bash: echo PATH_P_TV_SHOWS=$(PATH_P_TV_SHOWS) >> **/.env
- bash: echo PATH_P_MOVIES=$(PATH_P_MOVIES) >> **/.env
- bash: echo PATH_DOWNLOADS=$(PATH_DOWNLOADS) >> **/.env
- bash: echo PATH_LYCHEE=$(PATH_LYCHEE) >> **/.env
- bash: cat **/.env
- task: DockerCompose@0
  displayName: Docker Compose Config
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      TRAEFIK_ENTRY_POINT=${{variables.TRAEFIK_ENTRY_POINT}}
      TRAEFIK_ENTRY_POINT_PORT=${{variables.TRAEFIK_ENTRY_POINT_PORT}}
      TZ=Europe/Brussels
      DOMAIN_NAME=${{variables.VS_DOMAIN_NAME}}
      DOCKER_VOL_MOUNT=${{variables.DOCKER_VOL_MOUNT}}
      PATH_P_TV_SHOWS=${{variables.PATH_P_TV_SHOWS}}
      PATH_P_MOVIES=${{variables.PATH_P_MOVIES}}
      PATH_DOWNLOADS=${{variables.PATH_DOWNLOADS}}
      PATH_LYCHEE=${{variables.PATH_LYCHEE}}
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'config'
- task: DockerCompose@0
  displayName: Kill the running setup
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'down'
- task: DockerCompose@0
  displayName: Deploy the Mediaserver in Lab
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      TRAEFIK_ENTRY_POINT=${{variables.TRAEFIK_ENTRY_POINT}}
      TRAEFIK_ENTRY_POINT_PORT=${{variables.TRAEFIK_ENTRY_POINT_PORT}}
      TZ=Europe/Brussels
      DOMAIN_NAME=${{variables.VS_DOMAIN_NAME}}
      DOCKER_VOL_MOUNT=${{variables.DOCKER_VOL_MOUNT}}
      PATH_P_TV_SHOWS=${{variables.PATH_P_TV_SHOWS}}
      PATH_P_MOVIES=${{variables.PATH_P_MOVIES}}
      PATH_DOWNLOADS=${{variables.PATH_DOWNLOADS}}
      PATH_LYCHEE=${{variables.PATH_LYCHEE}}
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'docker-media-server'
    publishLocation: 'pipeline'


    
