# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master develop

pool:
  name: 'home-lab-build-docker'
steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      TRAEFIK_ENTRY_POINT=web
      TRAEFIK_ENTRY_POINT_PORT=80
      TZ=Europe/Brussels
      DOMAIN_NAME=$DOMAIN_NAME
      DOCKER_VOL_MOUNT=/mnt/dockervol
      PATH_P_TV_SHOWS=/mnt/pmedia/Tv Shows
      PATH_P_MOVIES=/mnt/pmedia/Film
      PATH_DOWNLOADS=/mnt/downloads
      PATH_LYCHEE=/mnt/lychee
    action: 'Combine configuration'
    outputDockerComposeFile: '$(Build.StagingDirectory)/docker-compose.yml'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      TRAEFIK_ENTRY_POINT=web
      TRAEFIK_ENTRY_POINT_PORT=80
      TZ=Europe/Brussels
      DOMAIN_NAME=$DOMAIN_NAME
      DOCKER_VOL_MOUNT=/mnt/dockervol
      PATH_P_TV_SHOWS=/mnt/pmedia/Tv Shows
      PATH_P_MOVIES=/mnt/pmedia/Film
      PATH_DOWNLOADS=/mnt/downloads
      PATH_LYCHEE=/mnt/lychee
    action: 'Run services'
    buildImages: false
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'docker-media-server'
    publishLocation: 'pipeline'

    
