version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    restart: always
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      #- "--api.entryPoing=admin"
      #- "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.webSecure.address=:443"
      #- "--entrypoints.webSecure.tls=true"
      #- "--entrypoints.admin.address=8080"
      - "--certificatesResolvers.myresolver.acme.email=${ACME_MAIL}"
      - "--certificatesResolvers.myresolver.acme.storage=acme.json"
      #      - "--certificatesResolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.httpChallenge=true"
      # - "--certificatesResolvers.myresolver.acme.entryPoint=webSecure"
      # - "--certificatesResolvers.myresolver.acme.domains.main=${DOMAIN_NAME}"
      - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web"
      # - "--certificatesResolvers.myresolver.acme.onHostRule=true"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    labels:
      #Need to check this. Api not workingy yet
      - "traefik.enable=true"
      - "traefik.http.routers.traefikapi.service=api@internal"
      - "traefik.http.routers.traefikapi.rule=Host(`api.traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefikapi.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.traefik-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-secure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.middlewares.traefik.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.entrypoints=webSecure"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #- "${DOCKER_VOL_MOUNT}/traefik/traefik.toml:/traefik.toml"
      - "${DOCKER_VOL_MOUNT}/traefik/acme.json:/acme.json"
      - "${DOCKER_VOL_MOUNT}/traefik/servers.toml:/servers.toml"
    networks:
      - proxy


networks:
  proxy:
    driver: bridge
