version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    restart: always
    container_name: "traefik"
    env_file: /home/mvhoof/docker-lab-01-agent/_work/1/a/environment.env
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      #- "--api.entryPoing=admin"
      #- "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.webSecure.address=:443"
      #- "--entrypoints.webSecure.tls=true"
      #- "--entrypoints.admin.address=8080"
      - "--certificatesResolvers.myresolver.acme.email=${ACME_MAIL}"
      - "--certificatesResolvers.myresolver.acme.storage=acme.json"
      #      - "--certificatesResolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.httpChallenge=true"
      # - "--certificatesResolvers.myresolver.acme.entryPoint=webSecure"
      # - "--certificatesResolvers.myresolver.acme.domains.main=${DOMAIN_NAME}"
      - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web"
      # - "--certificatesResolvers.myresolver.acme.onHostRule=true"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    labels:
      #Need to check this. Api not workingy yet
      - "traefik.enable=true"
      - "traefik.http.routers.traefikapi.service=api@internal"
      - "traefik.http.routers.traefikapi.rule=Host(`api.traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefikapi.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.traefik-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-secure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.middlewares.traefik.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.entrypoints=webSecure"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${DOCKER_VOL_MOUNT}/traefik/trafik.toml:/traefik.toml"
      - "${DOCKER_VOL_MOUNT}/traefik/acme.json:/acme.json"
      - "${DOCKER_VOL_MOUNT}/traefik/servers.toml:/servers.toml"


  # Management Platform Portainer to manage docker stuff
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DOCKER_VOL_MOUNT}/portainer:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.portainer-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-secure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.middlewares.portainer.redirectscheme.scheme=https"
      #- "traefik.http.routers.portainer.entrypoints.web.redirect=entryPoint=webSecure"
      #- "traefik.http.routers.portainer.entrypoints=webSecure"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer-secure.entrypoints=webSecure"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=myresolver"
      # Uncomment this label if your Traefik instance is using a specific Docker network and replace the network name 
      # This is not necessary if you set your default network in Traefik config/parameters
      #- "traefik.docker.network=dmz"