version: "3.3"

services:

  #First setup a reverse proxy to access everything that is running
  traefik:
    image: "traefik:latest"
    restart: always
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      #- "--api.entryPoing=admin"
      #- "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.webSecure.address=:443"
      #- "--entrypoints.webSecure.tls=true"
      #- "--entrypoints.admin.address=8080"
      - "--certificatesResolvers.myresolver.acme.email=${ACME_MAIL}"
      - "--certificatesResolvers.myresolver.acme.storage=acme.json"
#      - "--certificatesResolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.httpChallenge=true"
      # - "--certificatesResolvers.myresolver.acme.entryPoint=webSecure"
      # - "--certificatesResolvers.myresolver.acme.domains.main=${DOMAIN_NAME}"
      - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web"
      # - "--certificatesResolvers.myresolver.acme.onHostRule=true"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    labels:
      #Need to check this. Api not workingy yet
      - "traefik.enable=true"
      - "traefik.http.routers.traefikapi.service=api@internal"
      - "traefik.http.routers.traefikapi.rule=Host(`api.traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefikapi.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.traefik-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=sonarr-secure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.middlewares.traefik.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.entrypoints=webSecure"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
     # - "${DOCKER_VOL_MOUNT}/traefik/trafik.toml:/traefik.toml"
      - "${DOCKER_VOL_MOUNT}/traefik/acme.json:/acme.json"

  # Management Platform Portainer to manage docker stuff
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DOCKER_VOL_MOUNT}/portainer:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.portainer-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-secure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.middlewares.portainer.redirectscheme.scheme=https"
      #- "traefik.http.routers.portainer.entrypoints.web.redirect=entryPoint=webSecure"
      #- "traefik.http.routers.portainer.entrypoints=webSecure"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer-secure.entrypoints=webSecure"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=myresolver"
      # Uncomment this label if your Traefik instance is using a specific Docker network and replace the network name 
      # This is not necessary if you set your default network in Traefik config/parameters
      #- "traefik.docker.network=dmz"

  # TV Show Tool
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="${TZ}"
      #- UMASK_SET=022 #optional
    volumes:
      - "${DOCKER_VOL_MOUNT}/sonarr:/config"
      - "${PATH_P_TV_SHOWS}:/tv"
      - "${PATH_DOWNLOADS}:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.sonarr-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr.middlewares=sonarr-secure"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.middlewares.sonarr.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr-secure.entrypoints=webSecure"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.tls.certresolver=myresolver"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    #depends_on:
     # - nzbget
    volumes:
      - "${DOCKER_VOL_MOUNT}/radarr:/config"
      - "${PATH_DOWNLOADS}:/downloads"
      - "${PATH_P_MOVIES}:/movies"
    environment:
      - TZ="${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.radarr-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr.middlewares=radarr-secure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.middlewares.radarr.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr-secure.entrypoints=webSecure"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.tls.certresolver=myresolver"
    restart: unless-stopped

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    ports:
      - 4822:4822
    environment:
      - TZ="${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.guacd-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.guacd.middlewares=guacd-secure"
      - "traefik.http.routers.guacd.rule=Host(`ts.${DOMAIN_NAME}`)"
      - "traefik.http.routers.guacd.entrypoints=web"
      - "traefik.http.middlewares.guacd.redirectscheme.scheme=https"
      - "traefik.http.routers.guacd-secure.rule=Host(`ts.${DOMAIN_NAME}`)"
      - "traefik.http.routers.guacd-secure.entrypoints=webSecure"
      - "traefik.http.routers.guacd-secure.tls=true"
      - "traefik.http.routers.guacd-secure.tls.certresolver=myresolver"
    restart: unless-stopped

  # habridge:
  #   image: linuxserver/habridge
  #   container_name: habridge
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - SEC_KEY=${HABRIDGE_KEY}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${DOCKER_VOL_MOUNT}/habridge:/config
  #   ports:
  #     - 8080:8080
  #     - 50000:50000
  #   restart: unless-stopped
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - "${DOCKER_VOL_MOUNT}/duplicati/config:/config"
      - "${DOCKER_VOL_MOUNT}/duplicati/backups:/backups"
      - "${DOCKER_VOL_MOUNT}/duplicati/source:/source"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.duplicati-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.duplicati.middlewares=duplicati-secure"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.${DOMAIN_NAME}`)"
      - "traefik.http.routers.duplicati.entrypoints=web"
      - "traefik.http.middlewares.duplicati.redirectscheme.scheme=https"
      - "traefik.http.routers.duplicati-secure.rule=Host(`duplicati.${DOMAIN_NAME}`)"
      - "traefik.http.routers.duplicati-secure.entrypoints=webSecure"
      - "traefik.http.routers.duplicati-secure.tls=true"
      - "traefik.http.routers.duplicati-secure.tls.certresolver=myresolver"
    restart: unless-stopped
    
  #Picture time!
  lychee:
    image: linuxserver/lychee
    container_name: lychee
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="${TZ}"
    volumes:
      - "${DOCKER_VOL_MOUNT}/lychee:/config"
      - "${PATH_LYCHEE}:/pictures"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.lychee-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.lychee.middlewares=lychee-secure"
      - "traefik.http.routers.lychee.rule=Host(`lychee.${DOMAIN_NAME}`)"
      - "traefik.http.routers.lychee.entrypoints=web"
      - "traefik.http.middlewares.lychee.redirectscheme.scheme=https"
      - "traefik.http.routers.lychee-secure.rule=Host(`lychee.${DOMAIN_NAME}`)"
      - "traefik.http.routers.lychee-secure.entrypoints=webSecure"
      - "traefik.http.routers.lychee-secure.tls=true"
      - "traefik.http.routers.lychee-secure.tls.certresolver=myresolver"
    restart: unless-stopped

  # Some more fun tools
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    #depends_on:
    # - nzbget
    volumes:
      - "${DOCKER_VOL_MOUNT}/heimdall:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.heimdall-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.heimdall.middlewares=heimdall-secure"
      - "traefik.http.routers.heimdall.rule=Host(`dash.${DOMAIN_NAME}`)"
      - "traefik.http.routers.heimdall.entrypoints=web"
      - "traefik.http.middlewares.heimdall.redirectscheme.scheme=https"
      - "traefik.http.routers.heimdall-secure.rule=Host(`dash.${DOMAIN_NAME}`)"
      - "traefik.http.routers.heimdall-secure.entrypoints=webSecure"
      - "traefik.http.routers.heimdall-secure.tls=true"
      - "traefik.http.routers.heimdall-secure.tls.certresolver=myresolver"
    restart: unless-stopped

  # gitlab:
  #   image: gitlab/gitlab-ce:latest
  #   container_name: gitlab
  #   #restart: always
  #   hostname: "gitlab.{DOMAIN_NAME}"
  #   environment: 
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'http://gitlab.${DOMAIN_NAME}:80'
  #       gitlab_rails['gitlab_shell_ssh_port'] = 
  #   ports:
  #     - '2224:22'
  #   volumes:
  #     - "${DOCKER_VOL_MOUNT}/gitlab/config:/etc/gitlab"
  #     - "${DOCKER_VOL_MOUNT}/gitlab/logs:/var/logs/gitlab"
  #     - "${DOCKER_VOL_MOUNT}/gitlab/data:/var/opt/gitlab"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.gitlab.rule=Host(`gitlab.${DOMAIN_NAME}`)"
  #     - "traefik.http.routers.gitlab.entrypoints=${TRAEFIK_ENTRY_POINT}"
  #     - "traefik.http.services.gitlab.loadbalancer.server.port=80"