version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - dmz
      - backend
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.lab.vanhoof.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.docker.network=dmz"
    networks:
      - backend
  
  portainer:
    image: portainer/portainer
    restart: always
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.lab.vanhoof.me`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      # Uncomment this label if your Traefik instance is using a specific Docker network and replace the network name 
      # This is not necessary if you set your default network in Traefik config/parameters
      - "traefik.docker.network=dmz"

volumes:
  nfs_docker_example:
    driver_opts:
      type: "nfs"
      o: "addr=10.32.1.3,nolock,soft,rw"
      #device: ":/mnt/jet/jet-lab-docker"
      device: ":/mnt/tank/system/dockervol/nfs_test"
  portainer_data:
    driver_opts:
      type: "nfs"
      o: "addr=10.32.1.3,nolock,soft,rw"
      #device: ":/mnt/jet/jet-lab-docker"
      device: ":/mnt/tank/system/dockervol/portainer_data"

networks:
  dmz:
    driver: bridge
  backend:
    driver: bridge   