version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - dmz
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`lab.vanhoof.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - backend

volumes:
  nfs_docker_example:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.32.1.3,rw
      device: ":/mnt/jet/jet-lab-docker"   

networks:
  dmz:
    driver: bridge
  backend:
    driver: bridge   