version: "3.7"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - DMZ
    ports:
      - 9999:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle-rtr.rule=Host(`dozzle.${SUB_DOMAIN_1}`)"
      - "traefik.http.routers.dozzle-rtr.entrypoints=https"
      - "traefik.http.routers.dozzle-rtr.middlewares=middlewares-authentik@file"
      - "traefik.http.routers.dozzle-rtr.tls=true"
      - "traefik.http.routers.dozzle-rtr.tls.certResolver=azure"
      - "traefik.http.routers.dozzle-rtr.tls.domains[0].main=${DOMAIN_1}"
      - "traefik.http.routers.dozzle-rtr.tls.domains[0].sans=*.${SUB_DOMAIN_1}"
      - "traefik.docker.network=DMZ"

networks:
  DMZ:
    external:
      name: DMZ