version: "3.7"

services:
  minecraf-server-test:
    image: itzg/minecraft-server
    volumes:
      - ${DOCKER_VOLUMES}/minecraft_test:/data
    ports:
      - 25565:25565
    environment:
      MODE: creative
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped