version: "3.5"
services:
  organizr:
    image: linuxserver/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      -  "${DOCKER_VOL_MOUNT}/organizr:/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.organizr-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.organizr.middlewares=organizr-secure"
      - "traefik.http.routers.organizr.rule=Host(`organizr.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.organizr.entrypoints=http"
      - "traefik.http.middlewares.organizr.redirectscheme.scheme=https"
      - "traefik.http.routers.organizr-secure.rule=Host(`organizr.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.organizr-secure.entrypoints=https"
      - "traefik.http.routers.organizr-secure.tls=true"
      - "traefik.http.routers.organizr-secure.tls.certResolver=azure"
      - "traefik.http.routers.organizr-secure.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.organizr-secure.tls.domains[0].sans=*.${SUB_DOMAIN_NAME}"
    restart: unless-stopped