version: "3.5"

services:
  # Management Platform Portainer to manage docker stuff
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DOCKER_VOL_MOUNT}/portainer:/data"
    ports:
      - 9000:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.portainer-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-secure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.middlewares.portainer.redirectscheme.scheme=https"
      #- "traefik.http.routers.portainer.entrypoints.web.redirect=entryPoint=webSecure"
      #- "traefik.http.routers.portainer.entrypoints=webSecure"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certResolver=azure"
      - "traefik.http.routers.portainer-secure.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.portainer-secure.tls.domains[0].sans=*.${SUB_DOMAIN_NAME}"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9000"
      # Uncomment this label if your Traefik instance is using a specific Docker network and replace the network name 
      # This is not necessary if you set your default network in Traefik config/parameters
      #- "traefik.docker.network=noctrismediaserverdocker_proxy"
