version: "3.5"

services:
  parents_radarr:
    image: linuxserver/radarr
    container_name: parents_radarr
    #depends_on:
     # - nzbget
    volumes:
      - "radarr_parents_config:/config"
      - "${PARENT_DOWNLOAD}:/downloads"
      - "${PARENT_MEDIA}/Film:/movies"
    environment:
      - TZ="${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.parents-radarr-ssl.redirectscheme.scheme=https"
      - "traefik.http.routers.parents_radarr.middlewares=parents-radarr-ssl"
      - "traefik.http.routers.parents_radarr.rule=Host(`parents-radarr.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.parents_radarr.entrypoints=http"
      - "traefik.http.middlewares.parents_radarr.redirectscheme.scheme=https"
      - "traefik.http.routers.parents-radarr-ssl.rule=Host(`parents-radarr.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.parents-radarr-ssl.entrypoints=https"
      - "traefik.http.routers.parents-radarr-ssl.tls=true"
      - "traefik.http.routers.parents-radarr-ssl.tls.certResolver=azure"
      - "traefik.http.routers.parents-radarr-ssl.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.parents-radarr-ssl.tls.domains[0].sans=*.${SUB_DOMAIN_NAME}"
    restart: unless-stopped

volumes:
  radarr_parents_config: