version: "3.5"

services:
  parents_radarr:
    image: linuxserver/radarr
    container_name: parents_radarr
    #depends_on:
     # - nzbget
    volumes:
      - "radarr_parents_config:/config"
      - "${PARENT_DOWNLOAD}:/downloads"
      - "${PARENT_MEDIA}/Film:/movies"
    environment:
      - TZ="${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.radarr_parents-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr_parents.middlewares=radarr_parents-secure"
      - "traefik.http.routers.radarr_parents.rule=Host(`radarr-parents.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr_parents.entrypoints=http"
      - "traefik.http.middlewares.radarr_parents.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr_parents-secure.rule=Host(`radarr-parents.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr_parents-secure.entrypoints=https"
      - "traefik.http.routers.radarr_parents-secure.tls=true"
      - "traefik.http.routers.radarr_parents-secure.tls.certResolver=azure"
      - "traefik.http.routers.radarr_parents-secure.tls.domains[0].main=${SUB_DOMAIN_NAME}"
      - "traefik.http.routers.radarr_parents-secure.tls.domains[0].sans=*.${SUB_DOMAIN_NAME}"
    restart: unless-stopped

volumes:
  radarr_parents_config: