version: "3.5"

services:
  kids_radarr:
    image: linuxserver/radarr
    container_name: kids_radarr
    #depends_on:
     # - nzbget
    volumes:
      - "radarr_kids_config:/config"
      - "${KIDS_DOWNLOAD}:/downloads"
      - "${KIDS_MEDIA}/Films:/movies"
    environment:
      - TZ="${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.radarr_kids-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr_kids.middlewares=radarr_kids-secure"
      - "traefik.http.routers.radarr_kids.rule=Host(`radarr-kids.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr_kids.entrypoints=http"
      - "traefik.http.middlewares.radarr_kids.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr_kids-secure.rule=Host(`radarr-kids.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr_kids-secure.entrypoints=https"
      - "traefik.http.routers.radarr_kids-secure.tls=true"
      - "traefik.http.routers.radarr_kids-secure.tls.certResolver=azure"
      - "traefik.http.routers.radarr_kids-secure.tls.domains[0].main=${SUB_DOMAIN_NAME}"
      - "traefik.http.routers.radarr_kids-secure.tls.domains[0].sans=*.${SUB_DOMAIN_NAME}"
    restart: unless-stopped

volumes:
  radarr_kids_config: