version: "3.5"

services:
  parents_sonarr:
    image: linuxserver/sonarr
    container_name: parents_sonarr
    #depends_on:
     # - nzbget
    volumes:
      - "sonarr_parents_config:/config"
      - "${PARENT_DOWNLOAD}:/downloads"
      - "${PARENT_MEDIA}/Tv Shows:/tv"
    environment:
      - TZ="${TZ}"
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.parents_sonarr-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.parents_sonarr.middlewares=parents_sonarr-secure"
      - "traefik.http.routers.parents_sonarr.rule=Host(`sonarr-parents.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.parents_sonarr.entrypoints=http"
      - "traefik.http.middlewares.parents_sonarr.redirectscheme.scheme=https"
      - "traefik.http.routers.parents_sonarr-secure.rule=Host(`sonarr-parents.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.parents_sonarr-secure.entrypoints=https"
      - "traefik.http.routers.parents_sonarr-secure.tls=true"
      - "traefik.http.routers.parents_sonarr-secure.tls.certResolver=myresolver"
    restart: unless-stopped

volumes:
  sonarr_parents_config: