version: "3.5"

services:
  kids_sonarr:
    image: linuxserver/sonarr
    container_name: kids_sonarr
    #depends_on:
     # - nzbget
    volumes:
      - "sonarr_kids_config:/config"
      - "${KIDS_DOWNLOAD}:/downloads"
      - "${KIDS_MEDIA}/TV Shows:/tv"
    environment:
      - TZ="${TZ}"
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.sonarr_kids-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr_kids.middlewares=sonarr_kids-secure"
      - "traefik.http.routers.sonarr_kids.rule=Host(`sonarr-kids.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr_kids.entrypoints=http"
      - "traefik.http.middlewares.sonarr_kids.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr_kids-secure.rule=Host(`sonarr-kids.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr_kids-secure.entrypoints=https"
      - "traefik.http.routers.sonarr_kids-secure.tls=true"
      - "traefik.http.routers.sonarr_kids-secure.tls.certResolver=myresolver"
    restart: unless-stopped

volumes:
  sonarr_kids_config: