debug = true

logLevel = "ERROR"
defaultEntryPoints = ["https","web"]

[entryPoints]
  [entryPoints.web]
  address = ":80"
#    [entryPoints.web.redirect]
#    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "lab.vanhoof.me"
watch = true
exposedByDefault = false

[acme]
email = "mvhoof@vanhoof.me"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"