version: "3.5"
services:
  calibre-web_library:
    image: linuxserver/calibre-web
    container_name: parents_calibre-web_library
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
#      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - calibre_web_library:/config
      - "${PARENT_MEDIA}/Books/Van Hoof:/books"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.parents-calibreweb-library-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.parents-calibreweb-library.middlewares=parents-calibreweb-library-secure"
      - "traefik.http.routers.parents-calibreweb-library.rule=Host(`library.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.parents-calibreweb-library.entrypoints=http"
      - "traefik.http.middlewares.parents-calibreweb-library.redirectscheme.scheme=https"
      - "traefik.http.routers.parents-calibreweb-library-secure.rule=Host(`library.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.parents-calibreweb-library-secure.entrypoints=https"
      - "traefik.http.routers.parents-calibreweb-library-secure.tls=true"
      - "traefik.http.routers.parents-calibreweb-library-secure.tls.certResolver=azure"
      - "traefik.http.routers.parents-calibreweb-library-secure.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.parents-calibreweb-library-secure.tls.domains[0].sans=*.${SUB_DOMAIN_NAME}"
    restart: unless-stopped

volumes:
    calibre_web_library: