http:
  routers:
    hassio-prd-http:
      entryPoints:
        - http
      rule: Host(`hassio-prd.home.vanhoof.me`) || Host(`hassio.vanhoof.me`)
      middlewares: 
        - https-redirect@docker
      service: "hassio-prd-backend"
    hassio-prd-https:
        entryPoints:
          - https
        rule: Host(`hassio-prd.home.vanhoof.me`) || Host(`hassio.vanhoof.me`)
        service: hassio-prd-backend
        tls: {}
        certresolver: myresolver
  services:
    hassio-prd-backend:
      loadBalancer:
        servers:
          - url: "hhttp://10.32.1.8:8123"
  