http:
    routers:
      vcenter-http:
        entrypoints:
          - http
        rule: Host(`vcenter.lab.vanhoof.me`)
        middlewares: 
          - https-redirect@docker
        service: "vcenter"
    services:
      vcenter:
        loadBalancer:
          scheme: "https"
          servers:
            - url: "https://10.32.1.219/"
            