http:
    routers:
      vcenter-http:
        entryPoints:
          - http
        rule: Host(`vcenter.lab.vanhoof.me`)
        middlewares: 
          - https-redirect@docker
        service: "vcenter-ssl-backend"
    services:
      vcenter-ssl-backend:
        loadBalancer:
          scheme: "https"
          servers:
            - url: "https://10.32.1.219/"
            