version: "3.7"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DOCKER_VOLUMES}/syncthing:/config
     # - /:/serverroot
    ports:
      #- 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=943"
      - "traefik.http.routers.syncthing-rtr.rule=Host(`syncthing.${SUB_DOMAIN_1}`)"
      - "traefik.http.routers.syncthing-rtr.entrypoints=https"
      - "traefik.http.services.syncthing-svc.loadBalancer.server.port=8384"
      - "traefik.http.routers.syncthing-rtr.tls=true"
      - "traefik.http.routers.syncthing-rtr.tls.certResolver=azure"
      - "traefik.http.routers.syncthing-rtr.tls.domains[0].main=${DOMAIN_1}"
      - "traefik.http.routers.syncthing-rtr.tls.domains[0].sans=*.${SUB_DOMAIN_1}"