version: "3.5"

services:
# Heimdall Dashboard
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    #depends_on:
    # - nzbget
    volumes:
      - "${DOCKER_VOL_MOUNT}/heimdall:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.middlewares=heimdall-dashboard-secure"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.${SUB_DOMAIN_NAME}`) || Host(`dashboard.${DOMAIN_NAME}`)"
      - "traefik.http.routers.heimdall.entrypoints=http"
      - "traefik.http.routers.heimdall.middlewares=https-redirect"
      - "traefik.http.routers.heimdall-secure.rule=Host(`heimdall.${SUB_DOMAIN_NAME}`) || Host(`dashboard.${DOMAIN_NAME}`)"
      - "traefik.http.routers.heimdall-secure.entrypoints=https"
      - "traefik.http.routers.heimdall-secure.tls=true"
      - "traefik.http.routers.heimdall-secure.tls.certResolver=azure"
    restart: unless-stopped