version: "3.5"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - RUN_OPTS=run options here #optional
    volumes:
      - jackett_data:/config
      - ${PARENT_DOWNLOAD}/blackhole:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.jackett-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.jackett.middlewares=jackett-secure"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.jackett.entrypoints=http"
      - "traefik.http.middlewares.jackett.redirectscheme.scheme=https"
      - "traefik.http.routers.jackett-secure.rule=Host(`jackett.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.jackett-secure.entrypoints=https"
      - "traefik.http.routers.jackett-secure.tls=true"
      - "traefik.http.routers.jackett-secure.tls.certResolver=myresolver"
    restart: unless-stopped

volumes:
    jackett_data: