version: "3.5"

services:
#Picture time!
  lychee:
    image: linuxserver/lychee
    container_name: lychee
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="${TZ}"
    volumes:
      - "${DOCKER_VOL_MOUNT}/lychee:/config"
      - "${PATH_LYCHEE}:/pictures"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.lychee-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.lychee.middlewares=lychee-secure"
      - "traefik.http.routers.lychee.rule=Host(`lychee.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.lychee.entrypoints=web"
      - "traefik.http.middlewares.lychee.redirectscheme.scheme=https"
      - "traefik.http.routers.lychee-secure.rule=Host(`lychee.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.lychee-secure.entrypoints=webSecure"
      - "traefik.http.routers.lychee-secure.tls=true"
      - "traefik.http.routers.lychee-secure.tls.certResolver=azure"
      - "traefik.http.routers.lychee-secure.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.lychee-secure.tls.domains[0].sans=*.${SUB_DOMAIN_NAME}"
    restart: unless-stopped