version: "3.5"
services:
  # https://github.com/linuxserver/docker-nntp2nntp
  nntp2nntp:
    image: linuxserver/nntp2nntp
    container_name: nntp2nntp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DOCKER_VOL_MOUNT}/nntp2nntp:/config
    ports:
      - 1563:1563
    restart: unless-stopped