http:
  routers:
    hassio-prd-http:
      entryPoints:
        - http
      rule: Host(`hassio.vanhoof.me`)
      middlewares: 
        - https-redirect@docker
      service: "hassio-prd-backend"
    hassio-prd-https:
        entryPoints:
          - https
        rule: Host(`hassio.vanhoof.me`)
        service: hassio-prd-backend
        tls:
          certResolver: azure
          domains:
            - main: "vanhoof.me"
              sans:
                - "*.vanhoof.me"
                - "*.home.vanhoof.me"
  services:
    hassio-prd-backend:
      loadBalancer:
        servers:
          - url: "http://10.32.1.8:8123"