http:
  routers:
    hassio-dev-http:
      entryPoints:
        - http
      rule: Host(`hassio-dev.home.vanhoof.me`) || Host(`hassio-dev.vanhoof.me`)
      middlewares: 
        - https-redirect@docker
      service: "hassio-dev-backend"
    hassio-dev-https:
        entryPoints:
          - https
        rule: Host(`hassio-dev.home.vanhoof.me`) || Host(`hassio-dev.vanhoof.me`)
        service: hassio-dev-backend
        tls:
          certResolver: azure
          domains:
            - main: "vanhoof.me"
              sans:
                - "*.vanhoof.me"
                - "*.home.vanhoof.me"
  services:
    hassio-dev-backend:
      loadBalancer:
        servers:
          - url: "http://10.32.1.9:8123"
  