version: '3.7'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_VOLUME_PATH}/portainer:/data
    ports:
      - 9000:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.${SUB_DOMAIN1}`)"
      - "traefik.http.routers.portainer-rtr.entrypoints=https"
      - "traefik.http.services.portainer-rtr.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer-rtr.tls=true"
      - "traefik.http.routers.portainer-rtr.tls.certResolver=azure"
      - "traefik.http.routers.portainer-rtr.tls.domains[0].main=${DOMAIN1}"
      - "traefik.http.routers.portainer-rtr.tls.domains[0].sans=*.${SUB_DOMAIN1}"

networks:
  DMZ:
    external:
      name: DMZ