version: "3.5"

services:
  traefik:
    image: "traefik:latest"
    restart: always
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/traefik_data/servers"
      - "--providers.file.watch=true"
      - "--api=true"
      - "--api.dashboard=true"
      #- "--api.insecure=true"
      - "--certificatesResolvers.myresolver.acme.email=${ACME_MAIL}"
      - "--certificatesResolvers.myresolver.acme.storage=/traefik_data/acme.json"
      - "--certificatesResolvers.myresolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.httpChallenge=true"
      - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=http"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DOCKER_VOL_MOUNT}/traefik:/traefik_data"
    labels:
      - "traefik.enable=true"
      # define some generic middlewares
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.traefikbasicAuth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSW}"
      # Define API Redirect http listener
      - "traefik.http.routers.api.middlewares=https-redirect"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.rule=Host(`traefik.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.api.entrypoints=http"
      # Define API Https listener
      - "traefik.http.routers.api-ssl.middlewares=traefikbasicAuth"
      - "traefik.http.routers.api-ssl.service=api@internal"
      - "traefik.http.routers.api-ssl.rule=Host(`traefik.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.api-ssl.entrypoints=https"
      - "traefik.http.routers.api-ssl.tls=true"
      - "traefik.http.routers.api-ssl.tls.certresolver=myresolver"
      # try an existing backend
      #- "traefik.http.services.hassio.loadbalancer.server=http://10.32.1.8:8123"
      - "traefik.http.routers.hassio-test.rule=Host(`blabla.${SUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.hassio-test.entrypoints=http"
      - "traefik.http.routers.hassio-test.service=vcenter-ssl@file"