http:
    routers:
      sabnzbd-old-http:
        entryPoints:
          - http
        rule: Host(`sabnzbd-old.lab.vanhoof.me`) || Host(`sabnzbd-old.vanhoof.me`) || Host(`sabnzbd.vanhoof.me`)
        middlewares: 
          - https-redirect@docker
        service: "sabnzbd-old-backend"
      sabnzbd-old-https:
        entryPoints:
            - https
        rule: Host(`sabnzbd-old.lab.vanhoof.me`) || Host(`sabnzbd-old.vanhoof.me`) || Host(`sabnzbd.vanhoof.me`)
        service: sabnzbd-old-backend
        tls: {}
        certResolver: myresolver
    services:
      sabnzbd-old-backend:
        loadBalancer:
          servers:
            - url: "http://10.32.1.10:8080"