version: "3.3"

services:
# Heimdall Dashboard
  heimdall:
    image: linuxserver/heimdall
    env_file: ../environment.env
    container_name: heimdall
    #depends_on:
    # - nzbget
    volumes:
      - "${DOCKER_VOL_MOUNT}/heimdall:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.heimdall-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.heimdall.middlewares=heimdall-secure"
      - "traefik.http.routers.heimdall.rule=Host(`dash.${DOMAIN_NAME}`)"
      - "traefik.http.routers.heimdall.entrypoints=web"
      - "traefik.http.middlewares.heimdall.redirectscheme.scheme=https"
      - "traefik.http.routers.heimdall-secure.rule=Host(`dash.${DOMAIN_NAME}`)"
      - "traefik.http.routers.heimdall-secure.entrypoints=webSecure"
      - "traefik.http.routers.heimdall-secure.tls=true"
      - "traefik.http.routers.heimdall-secure.tls.certresolver=myresolver"
    restart: unless-stopped