version: "3.5"

services:
  emby:
    image: linuxserver/emby
    container_name: emby
    #depends_on:
     # - nzbget
    volumes:
      - "emby_config:/config"
      - "${PARENT_DOWNLOAD}:/downloads/parents"
      - "${KIDS_DOWNLOAD}:/downloads/kids"
      - "${PRIVATE_DOWNLOAD}:/downloads/private"
      - "${PARENT_MEDIA}/Tv Shows:/parents_tvshows"
      - "${PARENT_MEDIA}/Film:/parents_movies"
      - "${PARENT_MEDIA}:/parents_media"
      - "${KIDS_MEDIA}/TV Shows:/kids_tvshows"
      - "${KIDS_MEDIA}:/kids_media"
      - "${KIDS_MEDIA}/Films:/kids_movies"
    ports:
      - 8096:8096
      - 8920:8920
    environment:
      - TZ="${TZ}"
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    labels:
      - "traefik.enable=true"
      - "trafik.port=8096"
      - "traefik.http.middlewares.emby-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.emby.middlewares=emby-secure"
      - "traefik.http.routers.emby.rule=Host(`emby.${SUB_DOMAIN_NAME}`) || Host(`emby.${DOMAIN_NAME}`)"
      - "traefik.http.routers.emby.entrypoints=http"
      - "traefik.http.middlewares.emby.redirectscheme.scheme=https"
      - "traefik.http.routers.emby-secure.rule=Host(`emby.${SUB_DOMAIN_NAME}`) || Host(`emby.${DOMAIN_NAME}`)"
      - "traefik.http.routers.emby-secure.entrypoints=https"
      - "traefik.http.routers.emby-secure.tls=true"
      - "traefik.http.routers.emby-secure.tls.certResolver=azure"
      - "traefik.http.routers.emby-secure.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.emby-secure.tls.domains[0].sans=*.${SUB_DOMAIN_NAME}"
    restart: unless-stopped

volumes:
  emby_config: